# https://taskfile.dev

version: "3"

tasks:
  build-lambda:
    desc: Build docker image for lambda microservice
    vars:
      TAG: '{{ .TAG | default "test" }}'
    cmds:
      - |
        docker buildx build --no-cache \
                            --build-arg GOPROXY=direct \
                            --build-arg GONOPROXY="proxy.golang.org/*" \
                            --build-arg GOINSECURE="golang.org,google.golang.org,gopkg.in,k8s.io,sum.golang.org,sigs.k8s.io" \
                            -t lambda:{{ .TAG }} ./lambda

  run:
    desc: run the server locally
    vars:
      PORT: '{{ .PORT | default "8081" }}'
      TAG: '{{ .TAG | default "test" }}'
    cmds:
    - docker run -d -e APP_PORT={{ .PORT }} -p {{ .PORT }}:{{ .PORT }} lambda:{{ .TAG }}
