# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build docker image for lambda microservice
    vars:
      TAG: '{{ .TAG | default "test" }}'
    cmds:
      - |
        docker buildx build --no-cache \
                            -t lambda:{{ .TAG }} .
  build:proxy:
    desc: Build docker image for lambda microservice
    vars:
      TAG: '{{ .TAG | default "test" }}'
    cmds:
      - |
        docker buildx build --no-cache \
                            --build-arg GOPROXY=direct \
                            --build-arg GONOPROXY="proxy.golang.org/*" \
                            --build-arg GOINSECURE="golang.org,google.golang.org,gopkg.in,k8s.io,sum.golang.org,sigs.k8s.io,mvdan.cc,github.com,honnef.co,nullprogram.com,rsc.io" \
                            -t lambda:{{ .TAG }} .

  push:
    desc: Build docker image for lambda microservice
    vars:
      TAG: '{{ .TAG | default "test" }}'
      REGISTRY: '{{ .REGISTRY | default "ixxel" }}'
    cmds:
      - |
        docker tag lambda:{{ .TAG }} {{ .REGISTRY }}/lambda:{{ .TAG }}
        docker push {{ .REGISTRY }}/lambda:{{ .TAG }}

  run:docker:
    desc: run the server locally with Docker
    vars:
      PORT: '{{ .PORT | default "8081" }}'
      TAG: '{{ .TAG | default "test" }}'
    cmds:
    - docker run --name lambda -d -e APP_PORT={{ .PORT }} -p {{ .PORT }}:{{ .PORT }} lambda:{{ .TAG }}

  run:local:
    desc: run the server locally
    vars:
      PORT: '{{ .PORT | default "8081" }}'
    cmds:
    - export GOPROXY=direct 
    - export GONOPROXY="proxy.golang.org/*"
    - export GOPRIVATE="golang.org,google.golang.org,gopkg.in,k8s.io,sum.golang.org,sigs.k8s.io,mvdan.cc,github.com,honnef.co,nullprogram.com,rsc.io"
    - export GOINSECURE="golang.org,google.golang.org,gopkg.in,k8s.io,sum.golang.org,sigs.k8s.io,mvdan.cc,github.com,honnef.co,nullprogram.com,rsc.io"
    - go -C . mod tidy
    - go -C . run lambda.go
